-- GENERATED by scripts/generate-program-seed.mjs — do not edit by hand.
-- Source of truth: lib/core/registry.ts
-- Regenerate after any registry change, or the engine and the database will
-- disagree about a number a stranger is shown.
--
-- 8 programmes. Amounts are estimated RANGES with conditions
-- attached, never approvals.

insert into rift_programs (
  slug, name, administrator, type, funding_state,
  amount_min, amount_max, county, first_time_only, reopens, source_note,
  income_limit_note, price_cap_note, conditions, verified_on, verified_by
) values
  ('ga-dream', 'Georgia Dream Homeownership Program', 'Georgia Department of Community Affairs', 'deferred', 'open', 10000, 12500, null, true, null, 'DCA program page and participating lender confirmation', 'Household income limits apply and vary by county and household size.', 'Purchase price caps apply and are updated periodically.', array['Must use a participating Georgia Dream lender','Homebuyer education course required before closing','Must occupy the home as a primary residence','Minimum credit score and liquid asset limits apply']::text[], '2026-08-19', 'Kaleb'),
  ('atlanta-hob', 'Atlanta Housing Opportunity Bond down payment assistance', 'Invest Atlanta', 'forgivable', 'open', 10000, 20000, 'Fulton', true, null, 'Invest Atlanta program listing', 'Tiered by income band as a percentage of area median income.', 'Property must be inside the City of Atlanta limits.', array['Property must be within City of Atlanta boundaries','Forgiven over a residency period — leaving early can trigger repayment','Buyer contribution required from own funds','Homebuyer education required']::text[], '2026-08-19', 'Kaleb'),
  ('dekalb-whd', 'DeKalb County Workforce Enhancement / homebuyer assistance', 'DeKalb County Community Development', 'forgivable', 'open', 7500, 10000, 'DeKalb', true, null, 'County community development office, phone confirmation', 'Income at or below a set percentage of area median income.', 'Maximum purchase price set by the county and revised annually.', array['Property must be in unincorporated DeKalb or a participating city','Five-year residency requirement for full forgiveness','Counseling certificate required']::text[], '2026-07-28', 'Kaleb'),
  ('gwinnett-hap', 'Gwinnett County Homestretch down payment assistance', 'Gwinnett County', 'deferred', 'closed', 7500, 10000, 'Gwinnett', true, 'Expected to reopen when the next allocation is released', 'County housing office notice', 'Income limits by household size.', 'Purchase price cap applies.', array['Funding is allocated in rounds and is currently exhausted','Property must be located in Gwinnett County','Homebuyer education required']::text[], '2026-08-30', 'Kaleb'),
  ('cobb-dpa', 'Cobb County down payment assistance', 'Cobb County Community Development', 'forgivable', 'waitlist', 5000, 10000, 'Cobb', true, 'Applications accepted to a waiting list', 'County program page', 'Income limits by household size.', 'Purchase price cap applies.', array['Property must be in Cobb County','Residency period applies','Counseling required']::text[], '2026-08-11', 'Kaleb'),
  ('fhlb-atl', 'FHLB Atlanta First-time Homebuyer Product', 'Federal Home Loan Bank of Atlanta, via member lenders', 'grant', 'open', 12500, 15000, null, true, null, 'Member lender confirmation', 'At or below 80% of area median income.', 'No separate price cap; lender underwriting applies.', array['Must be originated through a participating FHLB member lender','Matched savings requirement — buyer funds are matched at a set ratio','Retention period applies','Funds are released on a first-come basis each program year']::text[], '2026-08-19', 'Kaleb'),
  ('employer-gift', 'Employer assisted housing and gift funds', 'Employer or family, via lender gift letter', 'grant', 'open', 2000, 8000, null, false, null, 'Lender guidance — general', 'No income limit; depends entirely on the source.', 'None.', array['Gift funds require a documented gift letter acceptable to the lender','Some employers offer forgivable housing benefits that go unclaimed','Source of funds must be seasoned or documented']::text[], '2026-06-02', 'Kaleb'),
  ('stale-example', 'Legacy county assistance pilot', 'Regional housing authority', 'forgivable', 'open', 5000, 8000, 'DeKalb', true, null, 'Original program announcement', 'Income limits apply.', 'Price cap applies.', array['Pilot program with limited allocation']::text[], '2026-04-02', 'Kaleb')
on conflict (slug) do update set
  name = excluded.name,
  administrator = excluded.administrator,
  type = excluded.type,
  funding_state = excluded.funding_state,
  amount_min = excluded.amount_min,
  amount_max = excluded.amount_max,
  county = excluded.county,
  first_time_only = excluded.first_time_only,
  reopens = excluded.reopens,
  source_note = excluded.source_note,
  income_limit_note = excluded.income_limit_note,
  price_cap_note = excluded.price_cap_note,
  conditions = excluded.conditions,
  verified_on = excluded.verified_on,
  verified_by = excluded.verified_by;
