-- ============================================================================
-- Three program records changed in lib/core/assistance.ts on 29 Sep 2026, and
-- rift_programs.rules (the full record the live matcher reads) still held the
-- old ones:
--   fulton-hop, gwinnett-homestretch  the higher cap for a newly built home
--     (newBuildMax), so a price between the two caps reads "only if the home
--     is newly built" instead of dropping the program;
--   atl-beltline-map  the higher amount is for public-sector employees and
--     long-term residents (Invest Atlanta's words), not "civil servants" (D25).
--
-- Only `rules` is written. The generated full upsert
-- (scripts/generate-assistance-sql.mjs) also resets verified_on, which would
-- undo the weekly check's renewals (D22). Generated from
-- the records; each value is JSON.stringify of the record, as the
-- generator writes it.
-- ============================================================================

begin;
update public.rift_programs set rules = '{"administrator":"Invest Atlanta","sourceType":"city","kind":"deferred","firstTime":"not-stated","price":null,"minCredit":null,"loanTypes":null,"combines":"unknown","funding":"confirm","sourceUrl":"https://www.investatlanta.com/homebuyers/homebuyer-programs-downpayment-assistance","sourceName":"Invest Atlanta, Homebuyer Programs & Downpayment Assistance","checkedOn":"2026-09-24","status":"active","slug":"atl-beltline-map","name":"Beltline Mortgage Assistance Program","terms":"A 0% soft second mortgage with a 15-year affordability period.","amount":{"max":20000,"occupations":{"max":30000,"who":["safety","educator","health","military"],"note":"Up to $30,000 for public-sector employees (such as police, firefighters, public school teachers, and city or county staff) and long-term residents. It depends on working for a government employer; Invest Atlanta confirms.","confirm":true}},"area":{"counties":["Fulton","DeKalb"],"within":"In the Beltline Tax Allocation District, subareas 1, 2, 3, 8, 9 and 10."},"income":{"kind":"ami","pct":140,"note":"Two income tiers, up to 120% and up to 140% of area median income."},"conditions":["Put in at least $1,500 of your own money","Homebuyer education","The home must be in an eligible Beltline subarea"]}'::jsonb where slug = 'atl-beltline-map';
update public.rift_programs set rules = '{"slug":"fulton-hop","name":"Fulton County Homeownership Program (HOP)","administrator":"Fulton County Department of Community Development","sourceType":"county","kind":"forgivable","terms":"A 0% deferred second mortgage with no monthly payment, forgiven over a 6- or 11-year affordability period while it stays your home.","amount":{"max":22500,"pctOfPrice":7.5},"area":{"counties":["Fulton"],"within":"Fulton County outside the City of Atlanta, Chattahoochee Hills, Johns Creek, Roswell, Sandy Springs and South Fulton."},"firstTime":"required","firstTimeNote":"Not owned a home in the last 3 years.","income":{"kind":"ami","pct":80},"price":{"max":347000,"upTo":false,"newBuildMax":367000,"note":"$367,000 for a newly built home."},"minCredit":{"score":600,"note":"The county recommends 600; the lender sets the minimum."},"loanTypes":null,"combines":"unknown","combinesNote":"Federal HOME funds: the county reviews any other assistance before approving.","conditions":["Use a HOP participating lender","Put in at least $500 of your own money","No more than $20,000, or 20% of the price, in savings (retirement accounts do not count)","At least 8 hours of homebuyer education","A real estate agent must represent you"],"funding":"confirm","sourceUrl":"https://www.fultoncountyga.gov/-/media/Departments/Community-Development/Homeownership-Program/Program-Overview-August-2025-HOP.pdf","sourceName":"Fulton County, HOP program overview and policy","checkedOn":"2026-09-24","sourceDated":"2025-08-01","status":"active"}'::jsonb where slug = 'fulton-hop';
update public.rift_programs set rules = '{"slug":"gwinnett-homestretch","name":"Gwinnett Homestretch Down Payment Assistance","administrator":"Gwinnett County","sourceType":"county","kind":"forgivable","terms":"A 0% deferred loan, forgiven after 5 years of living in the home.","amount":{"max":10000},"area":{"counties":["Gwinnett"]},"firstTime":"required","firstTimeNote":"Not owned a home for 3 years or more.","income":{"kind":"ami","pct":80},"price":{"max":371000,"upTo":false,"newBuildMax":425000,"note":"$425,000 for a newly built home, effective December 1, 2025."},"minCredit":{"score":580,"note":"At least one score above 580."},"loanTypes":null,"combines":"unknown","conditions":["HUD-approved pre-purchase counseling class","A single-family home or townhome that passes the county''s inspection","Housing costs at or under 43% of income, all debts at or under 55%"],"funding":"confirm","fundingNote":"The county set aside $200,000 for 2026, for at least 13 buyers.","sourceUrl":"https://www.gwinnettcounty.com/government/departments/planning-development/services/hud-programs/down-payment-assistance","sourceName":"Gwinnett County, Down Payment Assistance","checkedOn":"2026-09-24","status":"active"}'::jsonb where slug = 'gwinnett-homestretch';
commit;
